### ISSUE TITLE
the sample label jason file has format issue

### ISSUE THREAD

**Issue by ksssscrl** [Azure-Samples/cognitive-services-sample-data-files#46]
the sample label jason file has format issue. when I import it, it said "InvalidArgument: Invalid project json object. Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'ExportedDocumentClass' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path 'assets.documents[0].class', line 1, position 352. "

I notice someone raise the same issue a few days before, and I don't think it is already resolved

**Comment by diberry** [comment]
@ksssscrl Which file is having the issue?

**Comment by ksssscrl** [comment]
> 
[Custom single classification - WebOfScience.zip](https://github.com/Azure-Samples/cognitive-services-sample-data-files/files/9068561/Custom.single.classification.-.WebOfScience.zip)

webOfScience_labelsFile.json in the zip

**Comment by aahill** [comment]
Thanks for raising this issue, we've updated this sample file.
