### ISSUE TITLE
Duplicates in sample for multi-label classification

### ISSUE THREAD

**Issue by almudenaftourne** [Azure-Samples/cognitive-services-sample-data-files#52]
There are a few duplicate elements in the .json file containing the labels (movieLabels.json) for multi-label classification in this tutorial: https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/custom-text-classification/quickstart?tabs=multi-classification&pivots=language-studio#upload-sample-data-to-blob-container. If you follow it to the letter using Language Studio, it will throw an error mentioning these duplicates. 

<img width="260" alt="image" src="https://user-images.githubusercontent.com/6634091/211887268-83ec25ff-4637-4490-bc3f-609efc7b465f.png">

If you delete the duplicates, which are the final 11 elements in the list, it works.

**Comment by aahill** [comment]
Thanks for bringing this issue to our attention @almudenaftourne 

I've updated the data file to remove the duplicate values! The file should work now.
