### ISSUE TITLE
Naming Issue in Custom multi classification - movies summary.zip

### ISSUE THREAD

**Issue by HamletMonkey** [Azure-Samples/cognitive-services-sample-data-files#62]
File with Issue: **Custom multi classification - movies summary.zip**
Tutorial link: https://learn.microsoft.com/en-us/training/modules/enrich-search-index-using-language-studio/04-exercise-enrich-cognitive-custom-classes

There's a mismatch between 2 of the `.txt` filenames and the ones in JSON file - causing error when training the movie-genre-classifier.

![image](https://user-images.githubusercontent.com/85542530/221518721-22a1cbbc-40f6-4b70-85e4-3035b4c44351.png)

![image](https://user-images.githubusercontent.com/85542530/221518846-63ca35ab-18a0-4283-b742-a41e35711345.png)

**Comment by aahill** [comment]
Thanks for letting us know about this issue, the .json file has been updated.
